/**
 * A P1 session must fold to the same numbers after the upgrade as before it.
 *
 * This is the acceptance criterion of docs/MIGRATION-P1-P2.md, and it is not a
 * courtesy toward old data. DOMAIN.md §6 records that sessions predating later
 * checks are still in the database, and every one of them carries
 * `ExportRecord`s naming the counts, the coverage and the SHA-256 of a file
 * somebody uploaded into an ERP. A session that folds to a different number
 * after an upgrade is a session whose export record no longer describes it —
 * and there is no way to tell, afterwards, which of the two numbers the ERP
 * received.
 *
 * `p1-expected.json` was **generated by the P1 fold, before the P2 changes
 * landed**. It is not a transcription of what the P2 fold happens to do. If
 * this test fails, the fix is in `src/domain/fold.ts`; regenerating the fixture
 * to make it pass would delete the only evidence of what P1 did.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import {
  canonicalEvent,
  MemoryRepository,
  resolveAll,
  UnchainableEventError,
  undoLast,
  verifyChain,
  type CountEvent,
  type Session,
} from '../../src/domain';

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), '..', 'fixtures');

const log: { sessionId: string; events: CountEvent[] } = JSON.parse(
  readFileSync(join(FIXTURES, 'p1-log.json'), 'utf8'),
);
const expected: {
  resolutions: Array<{ idarticulo: number; state: string; qty?: number }>;
} = JSON.parse(readFileSync(join(FIXTURES, 'p1-expected.json'), 'utf8'));

function byItem(events: readonly CountEvent[]): Map<number, CountEvent[]> {
  const map = new Map<number, CountEvent[]>();
  for (const event of events) {
    if (event.idarticulo === null) continue;
    const bucket = map.get(event.idarticulo);
    if (bucket) bucket.push(event);
    else map.set(event.idarticulo, [event]);
  }
  return map;
}

describe('a captured P1 log folds identically after the upgrade', () => {
  it('is genuinely P1-shaped: no counterId, no retractsEventId, no hashes', () => {
    // Stated first, because everything below is worthless if the fixture has
    // quietly acquired P2 fields.
    for (const event of log.events) {
      expect(event.counterId).toBeUndefined();
      expect('retractsEventId' in event).toBe(false);
      expect(['set', 'add', 'unchanged', 'retract']).toContain(event.kind);
      expect(typeof event.idarticulo).toBe('number');
    }
    // And it exercises the paths that could have moved: an unscoped retraction,
    // a retraction followed by an `add`, a waiver over a count, a negative
    // `add` (P1's undo), two devices, and a count of zero.
    const kinds = new Set(log.events.map((e) => e.kind));
    expect([...kinds].sort()).toEqual(['add', 'retract', 'set', 'unchanged']);
    expect(new Set(log.events.map((e) => e.deviceId)).size).toBe(2);
    expect(log.events.some((e) => e.kind === 'add' && e.qty < 0)).toBe(true);
    expect(log.events.some((e) => e.kind === 'set' && e.qty === 0)).toBe(true);
  });

  it('folds item by item to exactly what P1 produced', () => {
    const actual = [...resolveAll(log.events)]
      .sort((a, b) => a[0] - b[0])
      .map(([idarticulo, resolution]) => ({
        idarticulo,
        state: resolution.state,
        ...(resolution.qty === undefined ? {} : { qty: resolution.qty }),
      }));

    // Item by item, not as a summary: a total that matched while two items had
    // swapped their quantities would pass a count comparison.
    expect(actual).toEqual(expected.resolutions);
  });

  it('keeps the unscoped retraction whole-item, which is the one that could break', () => {
    // 4471: set(4) then retract. Under scoped semantics a retraction naming
    // nothing would withdraw nothing and the item would still be counted at 4.
    // Rule 4 of the fold is what stops that.
    const resolutions = resolveAll(log.events);
    expect(resolutions.get(4471)).toEqual({ state: 'untouched' });
    // 1960: set(8), retract, add(2). The `add` resumes from zero rather than
    // from 8, because the retraction cleared the running value.
    expect(resolutions.get(1960)).toEqual({ state: 'counted', qty: 2 });
  });

  it('is unaffected by a P2 event arriving for a different item', () => {
    // The realistic upgrade path is not "P1 log, then P2 log". It is one
    // database holding both, and the fold has to leave the old rows alone.
    const withP2: CountEvent[] = [
      ...log.events,
      {
        id: 'p2-note',
        sessionId: log.sessionId,
        counterId: 'counter-ana',
        idarticulo: null,
        usuario: 'ana',
        zona: 'CAVA',
        at: '2026-04-30T14:00:00.000Z',
        deviceId: 'tablet-a',
        seq: 20,
        kind: 'note',
        texto: 'dos cajas sin código en el piso de la cava',
      },
    ];
    const actual = [...resolveAll(withP2)]
      .sort((a, b) => a[0] - b[0])
      .map(([idarticulo, r]) => ({
        idarticulo,
        state: r.state,
        ...(r.qty === undefined ? {} : { qty: r.qty }),
      }));
    expect(actual).toEqual(expected.resolutions);
  });

  it('still accepts every P1 event at the repository, unchanged', () => {
    // `validateEvent` grew three checks. None of them may reject data that is
    // already in the database — an event that cannot be re-appended is an
    // event that cannot be restored from a backup.
    const repo = new MemoryRepository();
    const session: Session = {
      id: log.sessionId,
      bodega: '01',
      fechaCorte: '2026/04/30',
      sourceHash: 'x'.repeat(64),
      createdAt: '2026-04-30T12:00:00.000Z',
      items: [],
    };
    return (async () => {
      await repo.createSession(session);
      for (const event of log.events) await repo.appendEvent(event);
      expect((await repo.eventsForSession(log.sessionId)).length).toBe(log.events.length);
    })();
  });
});

describe('what P1 data cannot do, stated so nobody assumes otherwise', () => {
  it('cannot be hashed: no counterId, and none is invented', () => {
    // The documented rule. P1 sessions stay local, read-only and unchained;
    // they are not migrated onto the server.
    for (const event of log.events) {
      expect(() => canonicalEvent(event)).toThrow(UnchainableEventError);
    }
  });

  it('cannot be pushed as a chain, and says so rather than half-succeeding', () => {
    const verdict = verifyChain(log.sessionId, 'counter-ana', log.events);
    expect(verdict.ok).toBe(false);
  });

  it('can still be undone, because undo is an action taken now', () => {
    // Undo deliberately changed: `add(-q)` is gone and undo is a targeted
    // withdrawal. That is not a migration break — no stored number moves — and
    // it works on P1 events, which is what matters for a session somebody
    // reopens after the upgrade.
    const items = byItem(log.events);
    const draft = undoLast(items.get(1181)!);
    expect(draft).toMatchObject({ kind: 'retract', retractsEventId: 'p1-0002' });
  });
});
