/**
 * Public surface of the counting domain.
 *
 * Note what is *not* here: nothing about tabs, CP850, `rawRow`, column order or
 * `Grupo1..5`. That vocabulary belongs to src/zeus/, which this package never
 * imports — see types.ts.
 */
export type {
  Item,
  ItemState,
  CountEvent,
  CountEventBase,
  SetCountEvent,
  AddCountEvent,
  UnchangedEvent,
  RetractEvent,
  NoteEvent,
  FinishEvent,
  ReopenEvent,
  SessionScopedEvent,
  QuantityEvent,
  CountEventDraft,
  CounterEventDraft,
  Session,
  SessionMeta,
  SessionSource,
  ExportRecord,
} from './types.js';
export {
  resolve,
  resolveAll,
  compareEvents,
  changesResolution,
  isItemEvent,
  undoLast,
  type ItemEvent,
  type Resolution,
} from './fold.js';
export {
  itemVariance,
  bookValue,
  exposureQuantity,
  exposureValue,
  type Variance,
  type VarianceClass,
} from './variance.js';
export {
  isNormalisedInstant,
  assertNormalisedInstant,
  nowInstant,
  INSTANT_PATTERN,
} from './time.js';
export {
  summarizeSession,
  resolveSession,
  isWriteOff,
  type SessionSummary,
  type ItemSummary,
  type UnverifiedItem,
  type Exposure,
  type Coverage,
  type SummaryOptions,
} from './session.js';
export {
  canonicalEvent,
  genesisHash,
  chainHash,
  chainEvents,
  headHash,
  verifyChain,
  checkFinishManifest,
  seqRanges,
  UnchainableEventError,
  canonicalAction,
  canonicalJson,
  actionGenesisHash,
  chainActionHash,
  verifyActionChain,
  sessionHash,
  type ChainLink,
  type ChainVerdict,
  type ChainableAction,
  type FinishManifest,
  type ManifestVerdict,
  type StoredAction,
  type StoredLink,
} from './chain.js';
export {
  REASSIGNABLE,
  actaLines,
  handoverRisk,
  planReassignment,
  reassignBlockers,
  sealOverrides,
  standingWaivers,
  type ActionPayload,
  type AgregarContadorPayload,
  type AnularWaiverPayload,
  type StandingWaiver,
  type WaiverPayload,
  type HandoverRisk,
  type Move,
  type NewCounter,
  type NewSection,
  type ReasignarPayload,
  type ReassignBlocker,
  type ReassignInput,
  type ReassignmentPlan,
  type RepointedSection,
  type ResolvedMove,
  type RetirarContadorPayload,
  type SellarSinRegistrosPayload,
  type SessionActionKind,
  type SessionActionRecord,
} from './actions.js';
export {
  deriveCounterEstado,
  postFinishSeqs,
  sessionReadyToSeal,
  type CounterSyncState,
  type CounterVerdict,
  type DeviceEstado,
  type SealBlocker,
  type SealOverride,
  type StoredCounterEvent,
} from './sync.js';
export {
  MemoryRepository,
  MemoryChain,
  type PendingOutbox,
  EventConflictError,
  SequenceConflictError,
  sameEvent,
  validateEvent,
  type CountRepository,
  type CounterChainRepository,
  type ChainedEvent,
  type SyncState,
  type DeviceRepository,
  type DeviceIdentity,
  type ExportRepository,
} from './repository.js';
export {
  deriveFamilies,
  familyPrefix,
  type FamilyGroup,
} from './families.js';
export {
  assignmentCoverage,
  unassignedByFamily,
  dispatchBlockers,
  sharedDispatchBlockers,
  type SharedDispatchInput,
  type Assignment,
  type AssignmentCoverage,
  type Counter,
  type CounterEstado,
  type CoverageGap,
  type DispatchBlocker,
  type DispatchInput,
  type Section,
  type SessionEstado,
} from './assignment.js';
export {
  counterItem,
  counterPayload,
  SECCION_COMPARTIDA,
  sharedScope,
  COUNTER_PAYLOAD_FIELDS,
  COUNTER_SESSION_FIELDS,
  COUNTER_COUNTER_FIELDS,
  COUNTER_SECTION_FIELDS,
  COUNTER_ITEM_FIELDS,
  NEVER_SENT_TO_A_COUNTER,
  type CounterItem,
  type CounterPayload,
  type CounterPayloadInput,
  type CounterSection,
  type CounterSessionView,
  type CounterView,
} from './counterView.js';
export { eventFromRow, type EventWire } from './wire.js';
export {
  annullable,
  reviewChecklist,
  reviewSession,
  waiverBlockers,
  waiverPreview,
  waiversToEvents,
  type AdvisoryItem,
  type Amendment,
  type ExplicitZero,
  type Overlap,
  type OverlapContribution,
  type Review,
  type ReviewCounter,
  type ReviewFlag,
  type ReviewInput,
  type ReviewNote,
  type ReviewNotes,
  type ReviewRow,
  type SupersededWaiver,
  type TrailingRetraction,
} from './review.js';
export {
  ownLog,
  ownNotes,
  ownSummary,
  registeredArticles,
  sectionProgress,
  type AssignedSection,
  type OwnEntry,
  type OwnSummary,
  type SectionProgress,
} from './ownWork.js';
