-- P2.3.5 — counter changes after dispatch.
--
-- Two things, and they are about different problems: somewhere to record an
-- admin's decisions, and something to make two admins reassigning at once
-- refuse rather than silently reverse each other.

-- ---------------------------------------------------------------------------
-- The admin's own chain.
--
-- Retiring a counter is a decision with consequences, made by a named person,
-- that an auditor will ask about — and until now there was nowhere to put one.
-- `events` is per counter and chained to counter identity, and nothing else in
-- this schema is sealed.
--
-- **Not a role column on `counters`.** That table carries a token, a bound
-- device, a `final_seq`, a manifest and four counting-specific states; an admin
-- has none of those meanings, and overloading it would hang four nullable
-- columns off the entity whose integrity the sealing gate reads.
--
-- P2.4 has the same problem and worse — a waiver is an admin vouching for a
-- book figure on a row nobody counted, which is the single most questionable
-- act in the whole process — so this is built here, once, and P2.4 adds its
-- kinds to it rather than inventing a second mechanism.
create table session_actions (
  -- Generated by the handler, like an event's, so the id is in the hash.
  id          uuid    primary key,
  session_id  uuid    not null references sessions(id) on delete cascade,
  -- **One chain per session, not one per admin.** Admin actions happen at a
  -- desk, one at a time; a single sequence is sufficient and is far easier to
  -- verify than several that would have to be interleaved afterwards.
  seq         integer not null,
  -- agregar_contador | retirar_contador | reasignar | sellar_sin_registros.
  -- P2.4 adds its own; the chain does not care which, and `canonicalAction`
  -- puts the kind inside the hash.
  kind        text    not null,
  -- `jsonb`, because these are heterogeneous and **none of them participates in
  -- the fold**. That is the whole difference from `events.cantidad text`, which
  -- is a string precisely because it does: a quantity is hashed as its shortest
  -- decimal representation and a `numeric` column a driver round-trips through a
  -- float would break the chain silently.
  --
  -- The payload is still hashed, so it still has to survive the round trip byte
  -- for byte. `jsonb` does not preserve key order, so the hash is taken over a
  -- key-sorted canonical rendering (`canonicalJson` in src/domain/chain.ts), and
  -- that function refuses anything but safe integers among the numbers — `1.0`
  -- and `1e2` do not come back out as they went in, and an admin action carries
  -- no quantity, so it costs nothing to forbid them.
  payload     jsonb   not null,
  -- Who decided, typed at the desk. There are no accounts (docs/BACKEND.md),
  -- and an action with nobody on it is exactly what this table exists to
  -- prevent — `canonicalAction` refuses to hash one.
  usuario     text    not null,
  -- The client's stamp, verbatim, as hashed. Text for the same reason
  -- `events.client_at` is: a `timestamptz` would be re-rendered on the way out
  -- and the hash would stop matching.
  client_at   text    not null,
  server_at   timestamptz not null default now(),
  prev_hash   text    not null,
  hash        text    not null,
  -- The constraint the whole append path is guarded on, and the reason two
  -- admins cannot both write action 7.
  unique (session_id, seq)
);

-- One session's actions in order. The unique constraint above already indexes
-- `(session_id, seq)`, so there is deliberately no second index here.

-- ---------------------------------------------------------------------------
-- Optimistic concurrency over the partition.
--
-- Two admins on the dispatch screen produced P2.2's transaction bug. Two admins
-- reassigning at once is the same failure with a worse blast radius: dispatch
-- at least refuses the loser outright, whereas the second reassignment would
-- quietly *reverse* the first — Pedro is given Luis's shelves, and thirty
-- seconds later the other laptop hands them back.
--
-- Bumped inside every reassignment transaction, sent by the client, and checked
-- under the row lock. A mismatch is a `409` and the screen reloads and re-plans;
-- **move lists are never merged**, because two partitions that each make sense
-- do not make sense unioned, and the admin is the only one who knows which one
-- is still what they meant.
--
-- `not null default 0` so every session already open has a version, and a
-- client that has never seen one sends `0` and is correct until the first
-- change.
alter table sessions add column assignments_version integer not null default 0;

-- ---------------------------------------------------------------------------
-- `counters.estado` gains `retirado`.
--
-- No DDL: the column is free text and always has been, deliberately — the state
-- machine lives in `src/domain/sync.ts` where both the server and the device
-- read it from one definition, and a check constraint here would be a second
-- copy that has to be migrated every time a state is added.
--
-- What is worth writing down is that `retirado` is the **only** state in that
-- column that is not derived from the chain. The other four are what the server
-- can see of what arrived; this one is a decision recorded in `session_actions`
-- with a reason, and it is sticky: a late push from a retired counter's tablet
-- is accepted, is attributed to them, and must not return them to `contando`.
-- `insertEventsStatements` guards on exactly that.
