/**
 * The launcher icons, drawn rather than dropped in.
 *
 * A tally group — four strokes and the fifth across them — because that is
 * what the app is, and because it survives being 48 pixels wide on a tablet
 * held at arm's length in a storeroom. No lettering: `conteo` at icon size is
 * a smudge, and the mark is read faster than a word anyway.
 *
 * Generated by this script rather than exported from a drawing tool so the
 * geometry is inspectable and the files can be rebuilt from source. Run:
 *
 *     node tools/make-icons.mjs
 *
 * No image dependency: PNG is a filter byte per row and a zlib stream, both of
 * which Node already has. Coverage is sampled 4x4 per pixel, which is enough
 * antialiasing for shapes made of round-capped lines.
 */
import { deflateSync } from 'node:zlib'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'public')

// theme.css, inverted: ink ground, paper mark. An icon sits on a wallpaper
// nobody chose for us, and the dark ground is the one that holds its edge on
// both a light and a dark launcher.
const INK = [0x17, 0x13, 0x10]
const PAPER = [0xfa, 0xf8, 0xf5]

/** Distance from a point to a segment — the whole of the rasteriser. */
function toSegment(px, py, x0, y0, x1, y1) {
  const dx = x1 - x0
  const dy = y1 - y0
  const len2 = dx * dx + dy * dy
  const t = len2 === 0 ? 0 : Math.max(0, Math.min(1, ((px - x0) * dx + (py - y0) * dy) / len2))
  return Math.hypot(px - (x0 + t * dx), py - (y0 + t * dy))
}

/**
 * The mark, as five round-capped strokes in a unit box.
 *
 * Four uprights and a diagonal laid across them, leaning the way a hand draws
 * it. Returned in the [0,1] square so one description serves every size.
 */
function tally() {
  const strokes = []
  const w = 0.125 // stroke width, in box widths
  const gap = (1 - 4 * w) / 3
  for (let i = 0; i < 4; i++) {
    const x = w / 2 + i * (w + gap)
    strokes.push([x, w / 2, x, 1 - w / 2, w])
  }
  // The fifth crosses the other four and overhangs both ends, which is what
  // makes it read as a strike rather than a fifth upright.
  strokes.push([-0.04, 0.86, 1.04, 0.2, w])
  return strokes
}

/**
 * @param size    pixels square
 * @param content the mark's box as a fraction of the canvas. Maskable icons
 *                get a smaller one: everything outside the middle 80% may be
 *                cropped away by the launcher, and a clipped tally is a bug
 *                nobody sees until it is on a home screen.
 */
function draw(size, content) {
  const px = new Uint8Array(size * size * 3)
  for (let i = 0; i < size * size; i++) {
    px[i * 3] = INK[0]
    px[i * 3 + 1] = INK[1]
    px[i * 3 + 2] = INK[2]
  }

  // The mark's box, centred, taller than wide the way a written tally is.
  const boxW = size * content
  const boxH = boxW * 1.15
  const left = (size - boxW) / 2
  const top = (size - boxH) / 2
  const strokes = tally().map(([x0, y0, x1, y1, w]) => [
    left + x0 * boxW,
    top + y0 * boxH,
    left + x1 * boxW,
    top + y1 * boxH,
    (w * boxW) / 2,
  ])

  const SAMPLES = 4
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      let hits = 0
      for (let sy = 0; sy < SAMPLES; sy++) {
        for (let sx = 0; sx < SAMPLES; sx++) {
          const cx = x + (sx + 0.5) / SAMPLES
          const cy = y + (sy + 0.5) / SAMPLES
          for (const [x0, y0, x1, y1, r] of strokes) {
            if (toSegment(cx, cy, x0, y0, x1, y1) <= r) {
              hits++
              break
            }
          }
        }
      }
      if (hits === 0) continue
      const a = hits / (SAMPLES * SAMPLES)
      const at = (x + y * size) * 3
      for (let c = 0; c < 3; c++) {
        px[at + c] = Math.round(INK[c] + (PAPER[c] - INK[c]) * a)
      }
    }
  }
  return px
}

function crc32(buf) {
  let c = ~0
  for (const byte of buf) {
    c ^= byte
    for (let k = 0; k < 8; k++) c = (c >>> 1) ^ (0xedb88320 & -(c & 1))
  }
  return ~c >>> 0
}

function chunk(type, data) {
  const head = Buffer.alloc(4)
  head.writeUInt32BE(data.length)
  const body = Buffer.concat([Buffer.from(type, 'latin1'), data])
  const tail = Buffer.alloc(4)
  tail.writeUInt32BE(crc32(body))
  return Buffer.concat([head, body, tail])
}

function png(size, rgb) {
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(size, 0)
  ihdr.writeUInt32BE(size, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 2 // truecolour
  // Each scanline carries a filter byte; 0 (none) compresses fine for flat art.
  const raw = Buffer.alloc(size * (size * 3 + 1))
  for (let y = 0; y < size; y++) {
    raw[y * (size * 3 + 1)] = 0
    Buffer.from(rgb.buffer, y * size * 3, size * 3).copy(raw, y * (size * 3 + 1) + 1)
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

// `any` fills the tile; `maskable` keeps clear of the crop.
const targets = [
  ['icon-192.png', 192, 0.66],
  ['icon-512.png', 512, 0.66],
  ['icon-maskable-512.png', 512, 0.46],
]

for (const [name, size, content] of targets) {
  const file = join(OUT, name)
  writeFileSync(file, png(size, draw(size, content)))
  console.log(name, size)
}

// The tab icon, as vector: the same five strokes, so a browser tab and a home
// screen show the same mark.
const svg = [
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">',
  `<rect width="64" height="64" rx="12" fill="#171310"/>`,
  '<g stroke="#faf8f5" stroke-width="5.28" stroke-linecap="round" fill="none">',
  ...tally().map(([x0, y0, x1, y1]) => {
    const bw = 64 * 0.66
    const bh = bw * 1.15
    const l = (64 - bw) / 2
    const t = (64 - bh) / 2
    const at = (v) => Math.round(v * 100) / 100
    return `<path d="M${at(l + x0 * bw)} ${at(t + y0 * bh)}L${at(l + x1 * bw)} ${at(t + y1 * bh)}"/>`
  }),
  '</g></svg>',
].join('')
writeFileSync(join(OUT, 'favicon.svg'), svg + '\n')
console.log('favicon.svg')
